require 'erb'
require 'xcodeproj'
require 'pathname'

def apimanager_h_template()
   %{
//
//  <%= @name %>.h
//
//  Copyright (c) 2018 longjianjiang. All rights reserved.
//
//  These api managers are generated by ruby script, you should not modify code
//  in this file.

#import <JXNetworking/JXNetworking.h>

@interface  <%= @name %> : JXBaseAPIManager <JXAPIManager>

@end
    }
end

class APIManagerH
  include ERB::Util
  attr_accessor :name, :template

  def initialize(name, template)
     @name = name
     @template = template
  end

  def render
     ERB.new(@template).result(binding)
  end

  def save(file)
     File.open(file, "w+") do |f|
       f.write(render)
     end
  end
end

def createHeader(name)
  fileName = "#{name}.h"
  manager = APIManagerH.new(name, apimanager_h_template)

  script_path = Pathname.new(__FILE__).realpath.to_s
  header_save_path = script_path[0, script_path.index('/ruby')] + '/MobYuWenApp/YWProject/Networking/APIManager'
  project_path = script_path[0, script_path.index('/ruby')] + '/MobYuWenApp.xcodeproj'

  manager.save(File.join(header_save_path, fileName))

  project = Xcodeproj::Project.open(project_path)
  target = project.targets.first

  # main_group只是工程所在目录
  group = project.main_group.find_subpath(File.join('MobYuWenApp', 'YWProject', 'Networking', 'APIManager'))
  # group.set_source_tree("SOURCE_ROOT")
  file_ref = group.new_reference(fileName)
  target.add_file_references([file_ref])
  project.save
end
